name: module3_task1
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  check_build:
    runs-on: ubuntu-18.04
    steps:
      - name: setup
        uses: actions/checkout@v3
      - name: initiate
        run: |
          cd module3_task1
          ./setup.sh
      - name: make
        run: |
          cd module3_task1
          make build
