name: module3_task2
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1 * *'
jobs:
  check_build:
    runs-on: ubuntu-18.04
    steps:
      - name: setup
        uses: actions/checkout@v3
      - name: initiate
        run: |
          cd module3_task2
          ./setup.sh
      - name: make
        run: |
          cd module3_task2
          make lint
          make unit-tests
          make validate
          make 
          make build
          make package
