name: module3_task1
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - run: |

          cd module3_task0/

      - run: |

          make build
